### ISSUE TITLE
Allowing for math in comments

### ISSUE THREAD

**Issue by matteobongio** [Dherse/codly#11]
Hi,

I'd like to be able to embed typst code, or at least just math in between lines of code, so as to have nicer comments.

**Comment by RosiePuddles** [comment]
how would you want this done? i'd assume an on-off toggle to allow maths inside `$` delimeters?
````typst
#codly(math-mode: true)

```rust
fn main() {
    let mut a = 0;
    // $a += 5$
    let a += 5;
    println!("{}", a);
}
```
````

maybe like that?

regardless of implementation, it's not possible to distinguish between code and comments so any code that used `$` (like PHP) wouldn't be able to use this because it might break

**Comment by Dherse** [comment]
This would prove tricky as comments aren't a thing that typst "tells codly", I am thinking of adding a tag to allow "escaping" default formatting, but it wouldn't work well across languages and would require manual parsing which I am not 100% in favor of.

I am closing this issue for the time being, but if you have an idea on how you'd like to see this done, feel free to reopen the issue. I would generally be hesitant to make code that has additional formatting as it defeats the purpose of raw text, but with a good enough solution (even if just on paper), I might do it either way.

**Comment by pmudry** [comment]
The `listings`package widely used in the LaTex world provides one handy option for that ([documented here](https://mirror.init7.net/ctan/macros/latex/contrib/listings/listings.pdf)). 

In short, special characters (which can be configured) are used as fences for toggling `raw` and `math` modes. This can be very handy for typesetting listings with equations in them for instance.
