### ISSUE TITLE
Indented code should be respected when line breaks in rendered code block

### ISSUE THREAD

**Issue by k4zuy** [Dherse/codly#14]
It would be really nice to have an option to activate respected code indentation when code line breaks in rendered document. 

(I could also help implementing this feature but don't know how to start)

Code indentation in vs code (line 928,929) with line break on and respected indentation 
<img width="686" alt="Bildschirmfoto 2024-05-13 um 09 44 32" src="https://github.com/Dherse/codly/assets/102243006/7fd9bff8-32b2-455c-9f3d-0b659120f061">
Code indentation in rendered document (line 4,5) without respected indentation (goal would be to have it like in vs code above)
<img width="608" alt="Bildschirmfoto 2024-05-13 um 09 45 20" src="https://github.com/Dherse/codly/assets/102243006/d957589b-9296-45d2-8ff8-5fb701c382a3">

**Comment by Dherse** [comment]
I agree with you, but it proves tricky, i'll have a look tomorrow.

**Comment by Dherse** [comment]
Actually, it was surprisingly easy, completed in 2b30708
