### ISSUE TITLE
`zebra-color: none` doesn't work as the comment suggests

### ISSUE THREAD

**Issue by emilyyyylime** [Dherse/codly#15]
In codly.typ a comment explains setting zebra-color to none would disable it, however I found that is not the case, and in fact it sets the default color. I would change it so the current behaviour is achieved with `auto` while disabling can be done with `false` (or `none`)

**Comment by k4zuy** [comment]
Is the reason for your proposal a different background color than white for the document?

**Comment by emilyyyylime** [comment]
not sure what you mean with 'for the document', but indeed I want to set a uniform background color for code blocks, and having to specify it twice slightly budges me

**Comment by k4zuy** [comment]
> for the document
I mean the whole project you are working on but now I understand what you mean. So you want that with the `zebra-color: auto` setting every second line of your code will automatically adapt to your defined `fill`color?

**Comment by emilyyyylime** [comment]
I imagine `zebra-color: auto` would produce the current behaviour, as auto is usually used for defaults. then `zebra-color: none` means the same as `zebra-color`=`fill`

**Comment by Dherse** [comment]
This was indeed a bug, it is fixed as of [6e4a60f](https://github.com/Dherse/codly/commit/6e4a60f46bf64f9eb1ee59d6f4455c9c7b5611fc)
