### ISSUE TITLE
Prefer taking `stroke` argument with stroke type rather than its fields

### ISSUE THREAD

**Issue by JamesxX** [Dherse/codly#19]
https://github.com/Dherse/codly/blob/88d90dca71e62a81bab019f540fd94f7ee3d5303/codly.typ#L84-L89

**Comment by Dherse** [comment]
This is the case as of [6e4a60f](https://github.com/Dherse/codly/commit/6e4a60f46bf64f9eb1ee59d6f4455c9c7b5611fc).
