### ISSUE TITLE
Code section background colour

### ISSUE THREAD

**Issue by Wenke-D** [Dherse/codly#21]
I really like this package, particularly the feature to define the language icon in the right top corner.

I see that we can disable the stroke to have a while background. But how can I have  a full customer background colour, for example full in blue.

**Comment by Dherse** [comment]
Hello,

You can do `codly(fill: none)` or `codly(fill: white)` for the whole background, if you're just interested in the language icon, it would be `codly(lang-fill: (_) => white)` or `codly(lang-fill: white)`, etc.

Let me know if this answers your question.

**Comment by Wenke-D** [comment]
Hello,

yes, this solve my questions, I would like to write this `codly(fill: yellow)`.

Thanks !
