### ISSUE TITLE
Highlighted code misaligned with other lines

### ISSUE THREAD

**Issue by Wenke-D** [Dherse/codly#22]
Hello again,

I found that highlighting code will make them unaligned with other lines.

For example, the `private` is not aligned with the `fun` keyword.

![1721307632669](https://github.com/user-attachments/assets/539200e5-3df0-4aac-ab8a-7692936fb021)

I presume it is caused by `highlight-inset`, but I can not set it as 0, as it will make the highlight quite ugly.

Is there any way to improve it ?

Thanks

**Comment by Dherse** [comment]
Yes, I noticed it too it’s in my plans to have a 1.0.1 with it fixed soon

Sébastien d'Herbais de Thun

**Comment by Dherse** [comment]
Fixed in #51 once it's merged.
