### ISSUE TITLE
what if i want to insert code from outside

### ISSUE THREAD

**Issue by Quaternijkon** [Dherse/codly#24]
i'm making template, i encounter a problem, i try to insert code into code-block, for example:
#let code=[pub fn hello()]
(i type it wrong purposely so that github won't convert it to something else)
...rust
[#code]
...
but it doesn't work, is it possible to fix that? thank you!

**Comment by Quaternijkon** [comment]
i fixed that!
#let code=[```rust pub fn hello()  ```] 
[#code]
which is so instinctive.

**Comment by Dherse** [comment]
Actually, if you use `raw(block: true)` you'll get full codly support ;)
Codly only acts on the `raw.where(block: true)` to avoid formatting non-block code blocks, in the future I might change that or make it configurable ;)
