### ISSUE TITLE
Codly is unable to detect figure block with custom kinds

### ISSUE THREAD

**Issue by Blokyk** [Dherse/codly#25]
## Problem

When using codly in figures with `kind != raw`, it's unable to detect that it *is* in fact in a figure, which breaks some features.

## Repro

````typ
#import "@preview/codly:1.0.0": *
#show: cody-init.with()

#figure(kind: "sample", supplement: "Sample")[
  #codly(annotations: ((start: 2, end: 2, label <ret_val>),));

  ```c
  int main() {
      return 1;
  }
  ```
]

As can be seen at @ret_val, blablabla...
````

This code will cause a panic with message: `codly: label ret_val is only allowed in a figure block`.

## Cause

This seems to be caused by this code, which only inserts the `codly-label` variable initialization around figures with `kind: raw`

https://github.com/Dherse/codly/blob/cea9d5cafdcf62c72d073e704a3c56e0a2f23ba4/codly.typ#L963-L970

## Workaround

For now, this can worked-around by adding these lines to your document:

```typ
#show figure: it => {
  if "label" in it.fields() {
    state("codly-label").update((_) => it.label)
    it
    state("codly-label").update((_) => none)
  } else {
    it
  }
}
```

This begs the question: why does `codly` restrict it to `kind: raw` figures right now? Could this cause a problem with other figure kinds, or interfere with other packages?

**Comment by Dherse** [comment]
My goal is indeed to limit the risks of interacting with other figure kinds and mostly to try and avoid causing documents not to converge which is a risk with state updates in contextual function/show rules. The workaround you listed is the proper and intended way of doing it manually.
