### ISSUE TITLE
`#set par(justify: true)` affects code formatting

### ISSUE THREAD

**Issue by DrRuhe** [Dherse/codly#26]
Hi, thanks for the lib. 
I noticed that `#set par(justify: true)` affects how code is formatted. 

See https://typst.app/project/rDWZvNPK0LKNweW5mBOTRP

**Comment by DrRuhe** [comment]
Could you just add a par(justify:false) to the codeblocks on the library side?

**Comment by Dherse** [comment]
I'll do that since I think in general this can be considered an upstream bug: https://github.com/typst/typst/issues/3454

**Comment by Dherse** [comment]
This is done in one of my recent commits. Will remove that line in the next version of Typst (0.13)

**Comment by DrRuhe** [comment]
Thanks!
