### ISSUE TITLE
inset adds space between lines not just around the border

### ISSUE THREAD

**Issue by robertosw** [Dherse/codly#27]
`inset: 8pt`
![image](https://github.com/user-attachments/assets/859b9c07-48b8-4864-b1fe-92107b2b67a8)

`inset` not specified
![image](https://github.com/user-attachments/assets/8698c649-39ba-4a2a-a9e0-4348541280d1)

**Comment by Dherse** [comment]
I see what you mean, I think a good solution would be an `inset` that can take a dict for different values, I'll see to implementing this when I have the time, feel free to open a PR in the meantime if you, or somebody else, feels like it!

**Comment by Dherse** [comment]
This was added in a recent commit. So closing it for now
