### ISSUE TITLE
Titles for code blocks?

### ISSUE THREAD

**Issue by J0shSkqlq** [Dherse/codly#28]
First of all, thank you for the amazing package! 
I am currently using it for my Master Thesis :)

I was wondering if there is a way to add a title to a code block like its done here:
https://backstage.io/docs/features/kubernetes/installation#:~:text=packages/app/src/components/catalog/EntityPage.tsx
They are using MkDocs for this where you can provide a title like this:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title

I think this would be a nice feature for codly too! 
Let me know incase it is already possible to do this and i just missed something.

Regards :)

**Comment by Dherse** [comment]
I really like the idea, I'll be trying to do it tonight, but no promises, I am swamped with work and I need my off time too :)

**Comment by Dherse** [comment]
Added in [a2c8946](https://github.com/Dherse/codly/commit/a2c89464ac3cc1bfb59c7a720cdb634e4d147298)
