### ISSUE TITLE
How to hiahlight c# code

### ISSUE THREAD

**Issue by hakureiR-eimu** [Dherse/codly#29]
I mean I found my cshrp code is't highlighted properly while the package worked well on C or Java 

what's wrong with it

**Comment by Dherse** [comment]
Can you send a link to a typst notebook with a small example please.

As far as I know, this shouldn't be a codly issue since it actually doesn't do any highlighting of its own. So the issue might be in typst but unless I have a working example I won't know.

**Comment by Dherse** [comment]
The correct name is not `cshrp` it's `cs` as per typst: https://typst.app/project/riJN8SJlxO6jmwWQCADByV
 
You can find the full list here, provided by Laurenz: https://github.com/typst/typst/issues/1511#issuecomment-1822459773
