### ISSUE TITLE
`local` function adds layout pass

### ISSUE THREAD

**Issue by otytlandsvik** [Dherse/codly#31]
It seems each use of `local` causes the compiler to do another pass to construct the layout of the document. Having too many calls to `local` in a document gives the warning `layout did not converge within 5 attempts`.

**Comment by Dherse** [comment]
Yes, this cannot be fixed until we have custom components :(
I know this sucks. I added `local` to try and make things easier, just using `codly(...)` before and after the codeblock yourself might be easier

**Comment by Dherse** [comment]
Actually, there is a way around it, but it won't be super nice, local will take the raw block as a value:
````typ
local(..., ```rs
pub fn hello(name: &str) {
    println!("Hello, {name}!");
}
```)
````

**Comment by Dherse** [comment]
Actually I found an even nicer way of doing it that doesn't abuse states (as much) :tada:

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/9301f9db-e30e-4458-a0ed-d8e2c6672f76)

Fixed in [0608632](https://github.com/Dherse/codly/commit/060863257fe53fd86ecc384ef8bc338a09cc3f57)

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/832e7dfb-eb4f-4af5-a3f7-82ba1ad6de12)

You can even nest them in the soon-to-be commit

**Comment by Dherse** [comment]
If you can test in your use case if it doesn't cause any issues (by manually importing codly.typ, args.json, and args.typ) in your project that would be super useful

**Comment by otytlandsvik** [comment]
Thanks for this fix! I can confirm that with the library from master, this seems to no longer be an issue. I tested it out with 20 `local` blocks, which produced no warning, whereas the compiler would warn me after only 5 before. Looking forward to your next release! :rocket:
