### ISSUE TITLE
How to prevent/change line spacing?

### ISSUE THREAD

**Issue by TimeTravelPenguin** [Dherse/codly#32]
I have been trying to work out why the line spacing gets bigger when using Codly. I can't find anything in the docs and it is affecting my own styles. Hence, I wish to disable any kind of styling that codly applies to the text's presentation.

Before:
<img src="https://github.com/user-attachments/assets/77f0e2a3-517a-486d-b021-9c13ee5929c1" width="400px">

After:
<img src="https://github.com/user-attachments/assets/b3aa8f96-78bb-4f41-8a93-fc0c6b408f48" width="400px">

Is there a way to change this? Is there anything else being changed?
I tried looking through the source code, but nothing stood out to me.

Thanks.

**Comment by Dherse** [comment]
Weirdly I had not gotten an email for this issue (or any other recent issues until today), really sorry about that. I'll have a look today

**Comment by Dherse** [comment]
Ok so it appears to be something because codly uses a grid rather than the "normal" line spacing. I'll add a parameter for it

**Comment by TimeTravelPenguin** [comment]
Awesome! Thanks, it will make things much more flexible to use

**Comment by Dherse** [comment]
@TimeTravelPenguin Can you provide me with an example code from your document please? (can be any code, just an example that shows the issue)

**Comment by TimeTravelPenguin** [comment]
> @TimeTravelPenguin Can you provide me with an example code from your document please? (can be any code, just an example that shows the issue)

@Dherse The entire code can be shown with the following example:

````typ
#import "@preview/codly:1.0.0": *

// Remove these lines to see the difference
#show: codly-init.with()
#codly(number-format: none, zebra-fill: none, stroke: none, display-icon: false, display-name: false)

```py
import pandas as pd

def preprocess_headers(data: pd.DataFrame) -> None:
    data.columns = data.columns.str.title()

    # Rename columns to PascalCase
    data.rename(
        columns={
            "Placeofbirth": "PlaceOfBirth",
            "Stageid": "StageID",
            "Gradeid": "GradeID",
            "Sectionid": "SectionID",
            "Raisedhands": "RaisedHands",
            "Visitedresources": "VisitedResources",
            "Announcementsview": "AnnouncementsView",
            "Parentansweringsurvey": "ParentAnsweringSurvey",
            "Parentschoolsatisfaction": "ParentSchoolSatisfaction",
            "Studentabsencedays": "StudentAbsenceDays",
        },
        inplace=True,
        errors="raise",
    )

    # Replace values with correct ones
    data.loc[data["Relation"] == "Mum", "Relation"] = "Mother"
    data.loc[data["Nationality"] == "KW", "Nationality"] = "Kuwait"
    data.loc[data["PlaceOfBirth"] == "KuwaIT", "PlaceOfBirth"] = "Kuwait"
    data.loc[data["StageID"] == "lowerlevel", "StageID"] = "LowerLevel"

    # Ensure all lowercase values are capitalized (ignores values like USA)
    for col in ["Nationality", "PlaceOfBirth"]:
        data.loc[data[col].str.lower() == data[col], col] = data[col].str.title()

    # Convert object columns to categorical
    data_obj_dtypes = data.select_dtypes(include="object")
    data[data_obj_dtypes.columns] = data_obj_dtypes.astype("category")

    # Give some categorical columns an order and explicit categories
    grade_ids = [f"G-{i:02d}" for i in range(1, 13)]
    data["GradeID"] = data["GradeID"].cat.set_categories(grade_ids, ordered=True)
    data["Class"] = pd.Categorical(data["Class"], ordered=True, categories=["L", "M", "H"])
```
````

**Comment by Dherse** [comment]
Thanks for the example, I think it's not ideal, but if you set the `inset` to `inset: 0.205em` in a call to `codly` you get essentially the same result visually. This is not so much an issue in Codly as it is a design choice to have larger line spacing (originally codly was written for my thesis and the goal was to have space for comments). Additionally, a lot of codly features (i.e highlights, etc.) depend on there being enough room to fit them. To look good, there must be both: enough room and always the same spacing/size (to avoid some lines being taller than others).

Therefore the solution to your issue is simple `#codly(inset: 0.205em)`, if you change the monospace font, you'll likely need to adjust this. This works in both codly 1.0.0 and the upcoming codly 1.1.0, also of note: I solved a bug with smart-indentation that makes these code blocks work with it :)

**Comment by TimeTravelPenguin** [comment]
Thanks for this! I understand that my use is perhaps more of an edge case. I cannot remember why I needed this, but it was likely because I wanted only the smart indenting. Regardless, this is more than sufficient for my needs!

**Comment by Dherse** [comment]
Yes I understand it's frustrating, but I just don't want to overspecialize some edge cases because otherwise for other users they might be surprised when combination of settings lead to specific behaviour. Therefore, the "idiomatic" way of doing what you want with codly is by setting the `inset`.
