### ISSUE TITLE
Add tabler-icons guide to README and docs

### ISSUE THREAD

**Issue by doabell** [Dherse/codly#33]
(I'm using the https://typst.app/ web app - awesome package.)

The README.md example [image](https://github.com/Dherse/codly/blob/cea9d5cafdcf62c72d073e704a3c56e0a2f23ba4/demo.png) and [code](https://github.com/Dherse/codly/blob/cea9d5cafdcf62c72d073e704a3c56e0a2f23ba4/README.md?plain=1#L22) don't match, until one finds a copy of `tabler-icons.ttf` and installs / uploads it.

1. Can codly bundle the TTF or WOFF2 fonts so that the example works out of the box?
2. It would be great to include a guide on how to use `tabler-icons`. Something like:
    1. Search for the desired icon on https://tabler.io/icons
    2. Click on the icon and note the hex, e.g. `fa53` for `brand-rust`.
    3. Change `fa53` to your icon's hex in `icon: text(font: "tabler-icons", "\u{fa53}"),`
    4. Download `tabler-icons.ttf` (perhaps from [jsdelivr](https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.19.0/dist/fonts/)) and put it into Typst, more info [here](https://typst.app/docs/reference/text/text/#parameters-font)

Thanks.

**Comment by Dherse** [comment]
As far as I know, it's not possible to currently bundle fonts so no. I might rework the example to just not include that. I will include a small section in the README on how to get them. Thanks
