### ISSUE TITLE
Adding Syntax For GDScript

### ISSUE THREAD

**Issue by Jazztache** [Dherse/codly#34]
Hello!

I want to have syntax highlighting for GDScript, the domain-specific language for Godot.

If there is an easy way to add it myself, I would be happy to take that route. The syntax is very similar to Python. There is also a known set of colours that is used for highlighting in the Godot editor under the default theme, so those colours should be used.

Thankyou!

**Comment by k4zuy** [comment]
@Jazztache Take a look at that:

https://typst.app/docs/reference/text/raw/

The parameters `syntaxes` and `theme` are what you are looking for. Maybe you are able to find those files for GDScript or you try to convert other file typs into those which you need for typst.

**Comment by Dherse** [comment]
Hey, indeed, adding custom syntaxes is done through the regular Typst system since codly doesn't actually do the syntax highlighting, rather providing extra features on top.

Thanks for your interest in Codly :)
