### ISSUE TITLE
Limited to one highlight per line

### ISSUE THREAD

**Issue by Aaron-Rumpler** [Dherse/codly#36]
Codly only shows the last highlight defined for each line. This is a regression from 1.0.0.

````typst
#import "./codly.typ": *

#set page(height: auto, width: 10cm, margin: 1em)
#show: codly-init.with()

#codly(
  highlights: (
    (line: 0, start: 14, end: 18, fill: blue),
    (line: 2, start: 5, end:10, fill: green),
    (line: 2, start: 24, end:38, fill: blue),
  ),
)

```java
public class MyApp {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
```
````
![Test](https://github.com/user-attachments/assets/e17651b1-52c5-48bf-b191-a0e8ad4b76df)

Swapping the highlight definitions shows the other highlight:
````typst
#import "./codly.typ": *

#set page(height: auto, width: 10cm, margin: 1em)
#show: codly-init.with()

#codly(
  highlights: (
    (line: 0, start: 14, end: 18, fill: blue),
    (line: 2, start: 24, end:38, fill: blue),
    (line: 2, start: 5, end:10, fill: green),
  ),
)

```java
public class MyApp {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
```
````
![Test](https://github.com/user-attachments/assets/e956d16e-db18-4dca-b27f-366b1380321e)

**Comment by Dherse** [comment]
I just got to documenting that part and noticed it too, trying to fix it now. Probably won't be done until tomorrow after work.

**Comment by Dherse** [comment]
Ok, figured it out, fixed in the next commit (will push this change tonight)

**Comment by Dherse** [comment]
See [cdffb47](https://github.com/Dherse/codly/commit/cdffb4773469d10f3813d91ba13b54ee3c7c6a4d)
