### ISSUE TITLE
Automatic offset for related code blocks

### ISSUE THREAD

**Issue by eduardz1** [Dherse/codly#39]
In the LaTeX listings package there is a nice feature where if you set a "name" for your code block, creating a new code block with the same name will cause the new block to have an offset corresponding to the other code blocks line number automatically applied.

![image](https://github.com/user-attachments/assets/33293105-98b9-440e-b894-ba85244de329)

Do you think it could be a good feature to add?

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/ac9c382a-89af-4a62-a3db-85485437af9f)



It was surprisingly simple to do. Should even work with `offset` on the other figures, etc. The only edge case I can think of which I will **not** fix is the case where you have a `range` set.

**Comment by Dherse** [comment]
Closed by [d8e8f24](https://github.com/Dherse/codly/commit/d8e8f244a470d3130f2820a4488f37dec58b14bf)

**Comment by eduardz1** [comment]
Thank you!
