### ISSUE TITLE
Clash between no line numbers and header. 

### ISSUE THREAD

**Issue by Alex-Muirhead** [Dherse/codly#40]
When using `number-format: none` to remove line numbers, a `header` cannot be used, as it explicitly uses `colspan: 2`. This could be fixed by changing the colspan depending on whether line numbers are displayed. 
https://github.com/Dherse/codly/blob/031485392978f4d871b8980e7671e5fb40c8c064/codly.typ#L1132-L1139

**Comment by Dherse** [comment]
Huh, I thought I had handled the edge case, I'll fix it since I am on my lunch break
