### ISSUE TITLE
Push 1.1.0 to typst universe

### ISSUE THREAD

**Issue by Glinte** [Dherse/codly#41]
I don't want to make a copy of codly for every single project on the web app just to have the new features like header :(

**Comment by Dherse** [comment]
Sorry but it's simply because it's not done 😬 I am super busy with work too and there are still quirks and bugs to fix. But you using it, and people opening issues for bugs, do help make it happen.

**Comment by Glinte** [comment]
Oh, I thought it is done because of the documentation

**Comment by Dherse** [comment]
Closed by release v1.1.0 38a6436
