### ISSUE TITLE
Unexpected Behaviour when Highlighting of Code

### ISSUE THREAD

**Issue by glennDittmann** [Dherse/codly#42]
First of all, great typst package. 💪🏻 

I have the following issue:
When I wanted to highlight code, the API allows me to specify the exact chars, where the highlight starts and ends, but the rendered output is different from that.

Example:
````typst
#codly(highlights: (
    (line: 0, start: 5, end: 17, fill:green),
  )) 
```python
def some_function():
  print(f"Codly is great!")
```
````
Gives me this output:
![Screenshot 2024-11-29 at 16 48 15](https://github.com/user-attachments/assets/ea0d0eb6-59c6-44e1-951f-a368bb36c556)

And even more, I get the same output from the image above for any value of end in 6..17.
When I change to 19 the closing bracket gets highlighted as well as expected (as this is the 19th char)

I could also help fix this, if you accept PRs.

**Comment by Dherse** [comment]
This is actually fixed on main, I just need to finish testing it and publish it!

It was fixed by 53bdb80

**Comment by glennDittmann** [comment]
Might be related to #22

**Comment by glennDittmann** [comment]
Ahhh nice, then let's close it. :)
