### ISSUE TITLE
high light line number start at 0 not 1

### ISSUE THREAD

**Issue by taooceros** [Dherse/codly#48]
Why is the `line` in highlight or other annotation function starts at 0 not 1, while the automatic line number starts at 1. This makes people a bit confused.

**Comment by Dherse** [comment]
Actually, after trying it out, I have come to agree with you and instead consider the one-indexed behaviour to make more sense and be correct.

**Comment by taooceros** [comment]
Yeah thanks. I am cs major and I use zero indexing all the time.
