### ISSUE TITLE
Better integration between skips and range

### ISSUE THREAD

**Issue by gamberoillecito** [Dherse/codly#49]
Hi, I created this issue because I think the current implementation makes it unnecessarily cumbersome to do the following:

I have a very long block of code of which I just want to show some sections. What I do now is either:

- Paste just the code I want to show into typst and then add `skips` to signal missing pieces of code. This has two drawbacks:

1. If I decide to add or remove pieces of code I have to adjust the `skips`
2. I have to manually count the number of lines that are not shown to make line numbering consistent

- Paste the whole block of code in typst and then combine `ranges` to show the parts of the code I'm interested with and  `skips` to signal where the code was removed from. 

What I think should exists is a hybrid between `range` and `skip` (something like `skip-range`) which behaves as a skip but, at the same time hides the specified range of lines from the rendered code.

Does this make sense? In my head it seems quite easy to implement and useful given the fact that all the basic building blocks seems to be there

Example:

```typst
#codly(skip-ranges: ((10,34), ))
# a very long piece of code ...
```

should generate something like:

![image](https://github.com/user-attachments/assets/3302195a-5b49-41ec-b2cd-13ca25dc5350)

**Comment by Dherse** [comment]
Hey, I see what you mean and I think it makes sense, I would probably call it something like "smart-skips" or something along those lines, I'll see what I can come up with, but it might take a little while, I am very short on bandwidth at the moment.

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/3b87bf49-c531-436c-9450-be2631eb42b4)

This is currently what I am settling on

**Comment by gamberoillecito** [comment]
It looks promising, I'll let you know for sure after trying it because I'm not sure I understand what you mean with first, last and rest. But I'm sure it is easy enough after seeing an example.

Thank you very much : )

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/b9959c86-8c2a-4019-8576-4e2c8283f229)

This is what it means (forgive the crude drawing)

**Comment by gamberoillecito** [comment]
That makes sense and seems very intuitive to use. Thanks a lot for your effort
