### ISSUE TITLE
should provide separate padding variables

### ISSUE THREAD

**Issue by max397574** [Dherse/codly#7]
Currently the padding of the codeblock lines also affects the language indicator block thing
Because of this I had issues with text being cut off when trying negative padding to safe space

it would be nice if there could be separate variables to configure the padding

**Comment by Dherse** [comment]
This is the case as of [6e4a60f](https://github.com/Dherse/codly/commit/6e4a60f46bf64f9eb1ee59d6f4455c9c7b5611fc)
