### ISSUE TITLE
Per-language numbering configuration

### ISSUE THREAD

**Issue by PgBiel** [Dherse/codly#8]
Hey!
I think it'd be nice to be able to configure the number format and toggle numbering for specific languages, through `codly-init`.

**Comment by Dherse** [comment]
This would prove tricky, right now I have made it much (much) easier to have local state (in [6e4a60f](https://github.com/Dherse/codly/commit/6e4a60f46bf64f9eb1ee59d6f4455c9c7b5611fc)) to do these things.

**Comment by Dherse** [comment]
@PgBiel I just figured out a way of doing it using the new `local` function:
```typ
#import "codly": *

#show: codly-init

#show figure: it => local(<your params based on `it.lang`>, it)

<your doc>
```

**Comment by PgBiel** [comment]
Interesting. Though I assume you mean `it.body.lang`, yeah?

**Comment by Dherse** [comment]
> Interesting. Though I assume you mean `it.body.lang`, yeah?

I meant raw not figure, my bad it's fixed now

**Comment by Dherse** [comment]
![image](https://github.com/user-attachments/assets/af8122eb-c3d2-44f3-8f99-f52e77c21c0c)

This is now an "officially supported" feature that is documented. There are two means of achieving it, both of which work.
